# -*- coding: utf-8 -*-
"""Day 5 Assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XM8MzlZLUHb1-IC5pqvQy4r7GaQVzZOK

Question 1 : [0,1,2,10,4,1,0,56,2,0,1,3,0,56,0,4] Sort by increasing order but all zeros should be at the last.
"""

list1 = [0,1,2,10,4,1,0,56,2,0,1,3,0,56,0,4]
list1.sort()
a = list1.count(0)
print(list1[a:]+list1[:a])

"""Question 2 : list1=[10,20,40,60,70,80] list2=[5,15,25,35,45,60] Merge these two sorted lists to produce one sorted list, and use for loop or while loop only once."""

list1 = [10,20,40,60,70,80]
list2 = [5,15,25,35,45,60]
list3 = list1+list2
list4 = []
for each in range(min(list3),max(list3)+1):
    if each in list3:
        list4.append(each)
print(list4)

