# -*- coding: utf-8 -*-
"""Day 4 assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DShgZxCeuDcJuW7e8DUqFPvvzffnNd2n
"""



"""Question 1 : Find all occurrence of substring in the given string "what we think we become; we are Python programmer". Print the index value."""

str1 = "what we think we become; we are Python programmer"
val1 = input("Enter the substring : ")
i = 0
while i != -1 :
  i = str1.find(val1, i+1)
  # if val1 in str1 :
  #   i += 1
  if i != -1:
    print(i)
  else :
    print(f"Above are the index of occurrences of your substring '{val1}'")

"""Question 2 : Explain "islower()" and "isupper()" using different kind of strings."""

val = input("Enter the string : ")
if val.isalpha():
  if val.islower():
    print(f"{val} is in lower case.")
  elif val.isupper():
    print(f"{val} is in upper case.")
  else:
    print(f"{val} has both upper and lower case.")
else:
  print(f"{val} has special characters and/or numbers.")

val = input("Enter the string : ")
if val.isalpha():
  if val.islower():
    print(f"{val} is in lower case.")
  elif val.isupper():
    print(f"{val} is in upper case.")
  else:
    print(f"{val} has both upper and lower case.")
else:
  print(f"{val} has special characters and/or numbers.")

val = input("Enter the string : ")
if val.isalpha():
  if val.islower():
    print(f"{val} is in lower case.")
  elif val.isupper():
    print(f"{val} is in upper case.")
  else:
    print(f"{val} has both upper and lower case.")
else:
  print(f"{val} has special characters and/or numbers.")

val = input("Enter the string : ")
if val.isalpha():
  if val.islower():
    print(f"{val} is in lower case.")
  elif val.isupper():
    print(f"{val} is in upper case.")
  else:
    print(f"{val} has both upper and lower case.")
else:
  print(f"{val} has special characters and/or numbers.")

