# -*- coding: utf-8 -*-
"""Day 6 Assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oRUgrKTPAbsuSrky7P4AgVtZtDjAzpo-

Question 1 : list1=[1,2,3,4,5,7,8] list2=["a","b","c","d","e"] Convert to a dictionary in one line code using list comprehension(without using zip method).
"""

A = [1,2,3,4,5,7,8]
B = ["a","b","c","d","e"]
print({A[i] : B[i]   for i in range( min(len(A),len(B)) ) })

