# -*- coding: utf-8 -*-
"""Day 3 Assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VEFKC7U3CK09cwaYEDj8o2eVOJ7W0qhc

Question 1 : Sum of "n" numbers using while loop.
"""

n=int(input("Enter a number : "))
num = n
sum1 = 0
incr = 0
print("Addition in descendoing order :")
while(n > 0):
    sum1 = sum1+n
    n=n-1
    incr = incr + 1
    print(f" Last {incr} number --> {sum1} ")
print(f"The sum of first {num} natural numbers is {sum1} ")

"""Question 2 : Take a number from user and find if it is a prime number or not."""

n=int(input("Enter a number : "))
if n > 1 :
  for each in range(2,n) :
    if n % each == 0 :
      print(f"{n} is not a prime number.")
      break
  else : 
      print(f"{n} is a prime number.")
else :
  print(f"{n} is equal to or less than 1, so {n} is not a prime number")

